<a href="https://colab.research.google.com/github/yalini154/1/blob/main/stats_pt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
upload = files.upload()

Saving Weather Dataset.csv to Weather Dataset.csv

In [3]:
data = pd.read_csv('Weather Dataset.csv')

In [4]:
data.head(5)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,month
0,2006-03-31 22:00:00+00:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,3
1,2006-03-31 23:00:00+00:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,3
2,2006-04-01 00:00:00+00:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,4
3,2006-04-01 01:00:00+00:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,4
4,2006-04-01 02:00:00+00:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,4

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            8760 non-null   object
 1   Summary                   8760 non-null   object
 2   Precip Type               8760 non-null   object
 3   Temperature (C)           8760 non-null   float64
 4   Apparent Temperature (C)  8760 non-null   float64
 5   Humidity                  8760 non-null   float64
 6   Wind Speed (km/h)         8760 non-null   float64
 7   Wind Bearing (degrees)    8760 non-null   float64
 8   Visibility (km)           8760 non-null   float64
 9   Loud Cover                8760 non-null   float64
 10  Pressure (millibars)      8760 non-null   float64
 11  Daily Summary             8760 non-null   object
 12  month                     8760 non-null   int64
dtypes: float64(8), int64(1), object(4)
memory usage: 889.8+ KB

In [6]:
data.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
month                       0
dtype: int64

In [7]:
mean_temp = np.mean(data['Temperature (C)'])
print("Mean Temperature is :", mean_temp)

Mean Temperature is : 11.215224505327246

In [8]:
var_temp = np.var(data['Temperature (C)'])
print("Variation of Temperature is :", var_temp)

Variation of Temperature is : 92.10832938614996

In [10]:
standard_deviation_temp = np.std(data['Temperature (C)'])
print("Standard Deviation of Temperature is :", standard_deviation_temp)

Standard Deviation of Temperature is : 9.597308444879218

In [13]:
for i in range(1, 13):
  month = data.loc[data["month"] == i]["Temperature (C)"]
  print("For month "+str(i))
  print("Mean temperature is"+ str(np.mean(month)))
  print("Standard deviation is"+ str(np.std(month)))

For month 1
Mean temperature is-1.677942054958184
Standard deviation is4.571201837602936
For month 2
Mean temperature is-0.06539351851851853
Standard deviation is4.5619751209500565
For month 3
Mean temperature is4.559274193548387
Standard deviation is5.716441576306105
For month 4
Mean temperature is12.635030864197532
Standard deviation is4.770260724427961
For month 5
Mean temperature is15.650731780167266
Standard deviation is4.744581723775079
For month 6
Mean temperature is19.35462191358025
Standard deviation is6.647687763465947
For month 7
Mean temperature is23.588664874551974
Standard deviation is5.348633953778177
For month 8
Mean temperature is19.478726105137397
Standard deviation is4.751328709657937
For month 9
Mean temperature is18.167731481481482
Standard deviation is4.813878512728091
For month 10
Mean temperature is12.84475806451613
Standard deviation is5.97854812659291
For month 11
Mean temperature is7.13770061728395
Standard deviation is4.32733696516641
For month 12
Mean temperature is2.218219832735962
Standard deviation is4.2767508050257605